import "./globals.css";
import Navbar from "./components/navbar";
import Wrapper from "./components/Session";

import { AppProvider } from "./context";  // Correct import

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>  {/* Wrap with the context provider */}
         
            <Wrapper>
              <Navbar />
              {children}
            </Wrapper>
        </AppProvider>
      </body>
    </html>
  );
}
